#import "../graphql/Place.fragment.gql"
#import "../graphql/User.fragment.gql"
#import "../graphql/Location.fragment.gql"
subscription placeCreated {
  placeCreated {
    ...PlaceFields
    location {
      ...LocationFields
    }
    user {
      ...UserFields
    }
  }
}
